The LSS NB with my extension for 3D plotting
astro-datalab/notebooks-latest pull request #164
Opened 2023-04-22 04:13 UTC by kareninysimba

* I added the extension for 3D plotting in the LSS NB to the science examples NBs
* There is a local file needed which is a live version of an extended virgo cluster catalog (ECV_coords_cz.csv)

2023-04-24 21:58 UTC, rnikutta requested changes
Thanks @kareninysimba for this PR.

Comments, suggestions, and requests:

- Remove this login cell, it's not needed, right?
```
from dl import authClient as ac
from getpass import getpass

token = ac.login("davalfher",getpass()) 
```
Instead, add a new Section "Authentication", by copying it straight from the NB template file (DataLabNotebookTemplate.ipynb)

- Update the version string in `__version__ = '20211122' # yyyymmdd`

- I suggest to add a new keyword to the `__keywords__` list in the first cell: '3d plot'; amd add it also to the keywords.txt file.

- Change in the first cell the `__author__` line to:
```
__author__ = 'Stephanie Juneau <stephanie.juneau@noirlab.edu>, David Herrera <david.herrera@noirlab.edu>, and the Astro Data Lab Team <datalab@noirlab.edu>'
```

- Change the line in the first Markdown cell to: "by Stéphanie Juneau, David Herrera, and the Astro Data Lab Team"

- Add a bullet point to the list under "Goals" about the 3d visualization.

- Remove "By D. Herrera" from just under the section "ACTUAL INTERACTIVE PLOT WITH GALAXIES IN 3D (RA, DEC and z)!!

- Remove the two hlines just above this section.

- Don't capitalize the section title. And no need for "Actual", nor for the two exclamation marks. This will do: "Interactive 3D plot (RA, DEC and z)"

- Make an anchor for this section, and add a link to the TOC that points to the new anchor.

- Correct typos, and change this sentence:

"We are no moving to a different area of the sky, where the Virgo cluster of galaxies is located. We want to indentify filaments and clumps of galaxies, but now moving around and 'traveling' through space."

to:

"We now turn to a different area of the sky. We want to identify filaments and clumps of galaxies in 3D, moving around and 'traveling' through space."

- Move the content of the imports cell in this section to the top imports section (there should only be one). Follow the sorting into std lib, 3rd party, DL imports. Remove that second imports cell.

- Remove this print statement: `print('You have successfully imported plotly libraries')`

- There are currently two subsections "Plotting in ACTUAL 3D". Make it only one.

- Don't capitalize, and don't write "actual". I.e., change to "Plotting in 3D".

- Change this text a bit to remove references to the Virgo cluster (see below):

"We want to take an interesting section of the sky, where we could observe galaxies clustering and/or filaments of the large scale structure of the universe, as we did in the previous section, EXCEPT, that now we can move through 'space' within those galaxies and see them from different points of view in that section of the universe.

We chose the section where the Virgo galaxy cluster is located, in order to map the galaxies in the area.

Next, we will get the SDSS data for coordinates and redshift, and define our boundaries, based on the approximate area of the Virgo cluster:"

- And don't capitalize "EXCEPT".

- Clean up by removing all debugging code snippets, commented-out lines, diagnostic stuff, for instance:
```
print('Time')

# This section is to be uncommented in case we are in an area around 0 degrees of RA:
# Convert RA range to [-180, 180] instead of [0, 360].
#RA -= 180
#print('Range for RA values after conversion: %s    %s' %(np.round(np.amin(RA),3),np.round(np.amax(RA),3)))
#print('Range for RA values after conversion: %s    %s' %(np.round(np.180,3),np.round(np.195,3)))

#'colorscale': 'Jet'

#'colorscale': 'Rainbow'

#zerolinecolor="white"

#camera_eye_x = 0.1,
#camera_eye_y = 0.10,
#camera_eye_z = 0.12,

#plot_figure.show()
```

- Please remove the last part (code and viz) where you plot the Virgo cluster members in white. As we discussed last week, the Virgo cluster is simply too close to show nicely as an example of LSS or galaxy clustering.

- Consequently, do a `git rm EVC_coords_cz.csv` as it's no longer needed.

- Also remove this cell (no longer needed)
```# Fetch the Virgo Cluster data
virgo = pd.read_table('/dlusers/davalfher/notebooks/03_ScienceExamples/LSS_3D/LargeScaleStructure/EVC_coords_cz.csv', sep = '\s+', header = 0) 

# This catalog includes heliocentric radial velocities v instead of z, for which an accepted approximation would be
# z = v/c, where c is the speed of light:

sl = 300000
RAv = virgo['RA1']
DECv = virgo['Dec1']
cz = virgo['cz']
rav_ = RAv
decv_ = DECv
zv_ = cz/sl
```

- The 3d plot with black background and tiny colorful dots looks really cool! But, the rendered graph has a large memory footprint (the ipynb file is 22MB!) There's two issues with this:
  - 1) The size of the ipynb file can be reduced if you commit the NB without rendered outputs. That is: start with a fresh kernel, run all the cells in sequence, then select Kernel-->Restart Kernel and clear all outputs. Then save the NB, and use that version to make a git commit. (it's only about 28 KB now)
  - 2) When the 3d plot is computed, and then loaded for display, it really wants to take a lot of the *client* RAM (i.e. the browser in the user's laptop eats up a lot of RAM). Would it be possible to reduce the number of data points used for plotting this graph? It's about 75K dots now. Maybe the RA, Dec, or z could be restricted further, without sacrificing the main point to show, namely the Large Scale Structure?

2023-06-15 15:28 UTC, rnikutta commented
@kareninysimba @jacquesalice @stephjuneau 
Could you please briefly review the new 3D plotting section in this NB? We'd like to merge it in time for the DL newsletter.
I made some edits to David's version from yesterday (described in the commit log).
Thank you!

2023-06-16 00:00 UTC, jacquesalice requested changes
@rnikutta @kareninysimba Thanks! Here are my comments:

1. Update all links to the Data Lab page to use `https` instead of `http` (seen in the following sections: Summary, Disclaimer, Query DECaLS Tractor Photometry Catalog, EXERCISE: Large-Scale Structures with Galaxy Colors).
2. In the "Visual Inspection of Large-Scale Structures" section, the link to the LS sky viewer gives me a "502 Bad Gateway". Change the link from `http` to `https`.
3. In the "Data query and preparation" subsection of "Large scale sctructure in 3D", it is mentioned that Planck2018 cosmology values are used to compute luminosity distance. Can you include a link to a paper or website that explains what Planck2018 cosmology values are?

Otherwise the 3D plot works well and is fun to play around with!! Nice job!

2023-06-16 00:18 UTC, stephjuneau commented
Planck2018 cosmology reference: https://ui.adsabs.harvard.edu/abs/2020A%26A...641A...6P/abstract

2023-06-16 00:54 UTC, stephjuneau requested changes

2023-06-16 00:54 UTC, stephjuneau commented on 03_ScienceExamples/LargeScaleStructure/LargeScaleStructureSdssLs.ipynb
I really like the new 3D plot! We can see some "Fingers of God" effect due to converting redshifts to a distance without correcting for proper motion of the galaxies (which we don't have information for). I suggest adding a sentence at the end and possibly pointing to the Wikipedia article (https://en.wikipedia.org/wiki/Redshift-space_distortions). Another nice explainer of this effect is: https://ned.ipac.caltech.edu/level5/March12/Coil/Coil4.html

It's also great that the 3D plot is based on data from the recent `sdss_dr17`!

Now for the first part of the notebook (which I wrote originally a long long time ago): we should replace older ls_dr3 and ls_dr4 schemas with the most recent: ls_dr10. This occurs in several places. Similarly sdss_dr13 can be replaced with sdss_dr17. This will change the join query as this one would now need to use 3 tables: 
- `ls_dr10.tractor`
- `ls_dr10.x1p5__tractor__sdss_dr17__specobj`
- `sdss_dr17.specobj`

I'll work on the joint query and suggest something in a separate comment. Together with these updates from ls_dr3/4 to ls_dr10, there are some changes to the text:
- Summary section (the last part and replacing the tables with the ones above)
- "Query DECaLS Tractor Photometry Catalog" section <-- Query the Legacy Surveys Tractor Photometry Catalog (and update the DR values)
- "Large-Scale Structures with LS Morphologies" section: 
```
Possible shapes for LS DR10:
<ul>
<li>PSF (point spread function: size will vary with the seeing of the observations)</li>
<li>REX (“round exponential” galaxies with a variable effective radius)</li>
<li>EXP (exponential profile; spiral galaxies)</li>
<li>DEV (deVaucouleurs profile; elliptical galaxies)</li>
<li>SER (Sersic profile)</li>
<li>DUP (set for Gaia sources duplicated by an extended source -- for information only, no flux)</li>
</ul>
```
You can then delete the next sentence: "Please note that starting in DR4 and in subsequent data releases, the SIMP model as been replaced with a REX model (Round Exponential)."

In the code cell below, you can replace `(result['type']=='COMP')` with `(result['type']=='SER')`

2023-06-16 01:42 UTC, stephjuneau commented
Alright, I got a new query to work (though it takes ~20 sec now instead of ~1 sec):
```
# ls_dr10.tractor                            # LS DR10 tractor photometry
# ls_dr10.x1p5__tractor__sdss_dr17__specobj  # LS DR10 pre-crossmatched to SDSS DR17 specobj
# sdss_dr17.specobj                          # SDSS DR17 specobj

# Write query statement (sql)
query = ("""
  SELECT L.ra, L.dec, L.type, L.sersic, L.g_r, L.r_z,
         S.z, S.ra as plug_ra, S.dec as plug_dec, S.class, S.veldisp, S.veldisperr 
  FROM ls_dr10.tractor AS L
  JOIN ls_dr10.x1p5__tractor__sdss_dr17__specobj AS X ON L.ls_id=X.id1 
  JOIN sdss_dr17.specobj AS S ON X.id2 = S.specobjid 
  WHERE L.ra BETWEEN %s AND %s AND L.dec BETWEEN %s AND %s AND (L.ra_ivar > 0) 
  LIMIT 100000
  """) % (126,131,7.,12.)  # small region

# L.ra, L.dec        = RA, Dec from Legacy Survey (LS) table    
# L.type             = object type (PSF, SIMP, EXP, DEV, COMP)
# L.g_r, L.r_z       = pre-computed g-r and r-z colors from photometry
# S.z                = redshift (z) from SDSS specObj table
# S.plug_ra, dec     = RA, Dec of SDSS fiber from specObj table
# S.class            = Source class (Star, Galaxy, QSO) from SDSS
# S.veldisp, veldisp = velocity dispersion (and error) from SDSS specObj table
#
# WHERE: requirement that RA & Dec coordinates are within a rectangular region

print(query)
```

Because of the new "type" in LS DR10, the code needs to be changed for the plotting with the morphological types. This works well:

```
# Select redshift slice and per type

# DEV or early type Sersic with steep index Sersic>=3
rdev = np.where(((result['type']=='DEV')|((result['type']=='SER')&(result['sersic']>=3))) & (result['z'] >0.105) & (result['z']<0.125))
# EXP or late type Sersic with index Sersic<2
rexp = np.where(((result['type']=='EXP')|((result['type']=='SER')&(result['sersic']<2))) & (result['z'] >0.105) & (result['z']<0.125))
# Intermediate with 2<= Sersic < 3
rint = np.where(((result['type']=='SER')&(result['sersic']>=2)&(result['sersic']<3)) & (result['z'] >0.105) & (result['z']<0.125))

# plot all points in red (all redshifts)
ax2.scatter(result['plug_ra'],result['plug_dec'],s=3,color='gray',marker='o',alpha=0.25)

# overplot in objects in narrow redshift slice color-coded blue (EXP or Late type) or red (DEV or Early type)
ax2.scatter(result['plug_ra'][rexp],result['plug_dec'][rexp],s=15,color='b')         # blue = EXP or late-type Sersic
ax2.scatter(result['plug_ra'][rcomp],result['plug_dec'][rcomp],s=15,color='orange')  # orange = Intermediate
ax2.scatter(result['plug_ra'][rdev],result['plug_dec'][rdev],s=15,color='r')         # red = DEV or early-type Sersic
```

I tested this and it worked but let me know if you run into problems!

2023-06-16 22:11 UTC, rnikutta commented
@stephjuneau could you please make a commit with your changes, on this branch? Easier than to have me or David add those changes.

2023-06-16 23:41 UTC, stephjuneau commented
@rnikutta & @kareninysimba : I believe I made all the changes to take care of @jacquesalice 's comments and my comments. I also updated the html version. Ready for final approval and merging!

2023-06-16 23:41 UTC, stephjuneau approved these changes

2023-06-17 00:30 UTC, rnikutta commented
Thank you @stephjuneau . Since we are updating this NB, I want to propose a few more (minor) edits:
- Remove "finger of God effect", simply stay with "possible distortion effects" and "redshift-space distortions". Both in Summary and in the very last paragraph of the NB.
- In Intro, change the wording about the 3d plot; it's not a "flat cube" based on RA, Dec, and z but we actually computed the distances, and then Cartesian coordinates X,Y,Z so that we can plot a proper cone / stencil.
-  "The column names and descriptions can be found from the [Data Lab Query Interface](https://datalab.noirlab.edu/query.php) or using the Table Access Protocol (TAP) service with, e.g., TOPCAT." --> We should add "and with `qc.schema()`, which works right here in the notebook."
- In-line comment line "# number of rows from LS DR3 tractor" --> "DR10"
- In-line comment line "# number of rows from SDSS specObj DR13:" --> DR17; and change code line below to use DR17 (it currently uses DR16; but tbl_stats isn't updated, so it returns 0. Propose to replace this call with `print(qc.query("select count(*) from sdss_dr17.specobj"))` which runs instantaneously for the small SDSS table (and it would show another way to get the row count).
- The section "Sanity check: RA, Dec positions from both tables" could use a sentence or two if motivation; what is being done here?
- In the text "Above, the left-hand panel shows a thin redshift slice (0.105 < z < 0.125, black symbols) among objects with redshifts from the spectroscopic SDSS DR13 sample (red symbols). " --> "SDSS DR17"
- Add year (2016) to "Lang, Hogg & Mykytyn"
- It seems that the cell right under the 3-panel figure that shows Elliptical, Spiral, Quasar images is hidden by default. Expand it?
Thank you!

2023-06-17 17:56 UTC, stephjuneau commented
Hi @rnikutta I just made all the new changes except that I don't see a hidden cell re: "It seems that the cell right under the 3-panel figure that shows Elliptical, Spiral, Quasar images is hidden by default. Expand it?". I just made a new HTML as well. Will push these new commits now.

2023-06-17 18:04 UTC, stephjuneau commented
Done! By the way, I saved the HTML without the 3D plot to make it smaller but saving it with the rendered 3D plot is actually interactive as HTML. Maybe in the future we could create a version of the interactive 3D plot for the website for extra funsies :-)

2023-06-17 18:55 UTC, rnikutta commented
Many thanks @stephjuneau ! Yep I don't see the hidden cell anymore either, must have been my butterfingers or something. Merging!

2023-06-17 18:55 UTC, merged