solving deprecated python code ahead of cloud deployment
astro-datalab/notebooks-latest pull request #173
Opened 2023-06-06 19:57 UTC by iglesu

2023-06-07 23:12 UTC, jacquesalice requested changes
I left a comment on each of the notebooks

2023-06-07 23:12 UTC, jacquesalice commented on 03_ScienceExamples/EmLineGalaxies/01_EmLineGalaxies_SpectraStack.ipynb
Notebook ran as expected with no errors or warnings. My only comment is to change the version date in the first cell to 20230607 (or whatever date you changed the notebook).

2023-06-07 23:12 UTC, jacquesalice commented on 03_ScienceExamples/GOGREEN_GalaxiesInRichEnvironments/3_GOGREENDr1ClusterMembership.ipynb
In the plot under the section titled "Select cluster with the highest dynamical mass", the black star that is supposed to indicate the position of the selected cluster isn't showing up on the plot...

<img width="707" alt="Screen Shot 2023-06-07 at 4 01 20 PM" src="https://github.com/astro-datalab/notebooks-latest/assets/51132735/72098b69-c9ef-4bd8-a344-e977e063592c">


It's _supposed_ to look like this:

<img width="744" alt="Screen Shot 2023-06-07 at 4 02 15 PM" src="https://github.com/astro-datalab/notebooks-latest/assets/51132735/5f1364da-a4d7-4138-b010-ed86a34193f1">

Also change the version date in the first cell to 20230607 (or whatever date you changed the notebook).

2023-06-07 23:12 UTC, jacquesalice commented on 03_ScienceExamples/GOGREEN_GalaxiesInRichEnvironments/4_GOGREENDr1Spec1DRedshift.ipynb
Notebook ran as expected with no errors or warnings. My only comment is to change the version date in the first cell to 20230607 (or whatever date you changed the notebook).

2023-06-10 05:35 UTC, rnikutta commented
Hi @iglesu and @jacquesalice I've pushed a commit to this branch, fixing all issues (I think):
- Deprecation of `np.filter.filterwarnings()`: instead of a global `import warnings; warnings.filterwarnings('ignore')` now using the more narrow `np.seterr(divide='ignore')` or `np.seterr(invalid='ignore')` or both.
- Deprecation of `pd.append()`. Now using `pd.concat()`.
- Fixed a bug in a function in NB 3_GOGREENS..., and its call, which prevented a star symbol to be plotted.
- Replaced the `label=str(np.int(snr))` issue with the cleaner `label="%d" % snr`
- Updated version stamps in these four NBs.
- Added HTML rendered versions too.

Tested all four NBs on gp12 and GCP, they now run fine. Will merge this PR.

2023-06-10 05:36 UTC, merged