Updated all the notebooks and the README file
astro-datalab/notebooks-latest pull request #207
Opened 2023-11-29 17:54 UTC by Ragadeepika-Pucha

@rnikutta @stephjuneau @jacquesalice - I updated the DESI-related notebooks and the associated ReadMe File:

- I modified the cell containing the redshift distribution plot to include a for-loop over the targeting classes. I did not want to include a plotting function - because I personally do not like to include functions in the middle of the cell without proper doc-string. I can change it if the current version is not good?
- I updated my affiliation and contact information.
- I added the authentication cell to the DESI-EDR with DESI kernel and DESI/SDSS comparison notebooks, to be consistent with the DESI-EDR Py3 notebook.
- I added a bullet regarding the Py3 notebook in the ReadMe file.

Let me know if anything else needs to be updated/changed.
Thank you!

2023-11-30 21:42 UTC, jacquesalice requested changes
Hi @Ragadeepika-Pucha , I think it all looks good! Only one small suggested addition to the README :-)

2024-02-28 19:43 UTC, rnikutta commented on 03_ScienceExamples/DESI/README.md
>  ## How-to folder: `04_HowTos/`
@Ragadeepika-Pucha @stephjuneau Hi, what's the status of this PR? Thanks.

2025-07-16 23:07 UTC, rnikutta commented on 03_ScienceExamples/DESI/README.md
>  ## How-to folder: `04_HowTos/`
@Ragadeepika-Pucha and @stephjuneau one last ping... May I close this PR without merging it? Or is it still relevant?

2025-07-17 05:46 UTC, rnikutta commented on 03_ScienceExamples/DESI/README.md
>  ## How-to folder: `04_HowTos/`
@Ragadeepika-Pucha your call, thank you.

2025-07-18 21:41 UTC, Ragadeepika-Pucha commented on 03_ScienceExamples/DESI/README.md
>  ## How-to folder: `04_HowTos/`
Hi @rnikutta - I think it is still relevant. The main things are 1) the cell with the updated redshift distribution, 2) the authentication cell to be consistent, and 3) an update regarding my affiliation. If there is not much conflict, we can merge it. There might be changes only with the EDR notebooks, from what I remember. It will not affect the SDSS vs. DESI notebook. Otherwise, we can create a separate PR for these three points.

2025-07-19 05:33 UTC, rnikutta commented
Thank you @Ragadeepika-Pucha for checking this out. As you can see, the files in your PR all ave conflicts with the newer files in 03_ScienceExamples/DESI/. The obvious difference is that the files in that directory have been renamed and adapted in the meantime to use DESI DR1 (from EDR).

Given that your changes are probably many fewer, would you mind:

- Closing this PR without merging.
- Making a new branch off of new current 'master'.
- Redoing your edits there (you will have new file names automatically).
- And finally making a new PR?

I suspect this would be much easier and faster than trying to resolve the possibly many conflicts in the current PR.

Thank you!

2025-07-21 18:03 UTC, rnikutta commented
Closing as per agreement. @Ragadeepika-Pucha will make a new PR, based off of the current master branch, thank you!

2025-07-21 18:03 UTC, closed without merging