Fixed typos and stylistic issues in the notebooks
astro-datalab/notebooks-latest pull request #220
Opened 2024-05-17 19:33 UTC by KeenanFiedler

I fixed several typos throughout the notebooks and fixed some odd font size mismatches in one notebook.

2024-05-17 21:50 UTC, rnikutta requested changes
Thanks for the PR @KeenanFiedler Only change request:

- In 03_ScienceExamples/GalacticStructure/StarClustersGaiaDR3.ipynb and DR2.ipynb, pdate 'cartesian' to 'Cartesian' (it's in a comment line)

2024-05-29 19:22 UTC, jacquesalice commented
Hi @KeenanFiedler can you remove these 2 files from this PR? :

03_ScienceExamples/GalacticStructure/StarClustersGaiaDR2.html
03_ScienceExamples/GalacticStructure/StarClustersGaiaDR2.ipynb

Since they were removed in PR #222

2024-05-30 01:00 UTC, rnikutta commented
Yep, there is a conflict now because of that. @KeenanFiedler simply get on this branch, do a `git rm filename` for both files, commit, and push, this should fix it.

2024-05-30 19:06 UTC, jacquesalice approved these changes

2024-05-30 19:06 UTC, merged